### ISSUE TITLE
0.0.15: Too many positional arguments for Object.hash()

### ISSUE THREAD

**Issue by dluksza** [rrousselGit/freezed#531]
**Describe the bug**
After updating freezed version to v0.0.15, re-generating objects I've got compilation errors:

```
Error: Too many positional arguments: 20 allowed, but 23 found.
  Try removing the extra positional arguments.
    int get hashCode => Object.hash(
```

Looks like new version doesn't like objects that have lots of properties. We don't always control the amount of data stored in an object and how many properties it has. Especially when dealing with third-party REST API (which freezed is soo good at) it is possible to run into objects that have more than 20 propertis.

**To Reproduce**

Just create a freeezed class with over 20 properties.

**Expected behavior**
The number of properties in object should not be limited. Freezed should work with classes that have 3 and 300 properites.

**Comment by rrousselGit** [comment]
That's interesting and scary at the same time. But I'll provide a fix
